[project]
name = "t8apicliente"
version = "0.1.0"
description = "Paquete de python para obtener y manipular los datos recolectados de la API de un T8"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "build>=1.4.0",
    "click>=8.3.1",
    "matplotlib>=3.10.8",
    "pandas>=3.0.0",
    "requests>=2.32.5",
    "scipy>=1.17.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "pytest>=9.0.2",
    "ruff>=0.14.14",
]

[tool.ruff]
line-length = 88
lint.select = ["ANN", "Q", "E", "F", "UP", "B", "I", "Q"]
lint.ignore = []
lint.exclude = []

[project.scripts]
t8-cli = "t8_client.cli:cli"
